=== chibios-upstream/chibios/os/test/ftl/schema/unittest.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:complexType name="instanceType">
      <xs:sequence>
        <xs:element name="description" type="descriptionType"
          maxOccurs="1" minOccurs="1">
        </xs:element>
        <xs:element name="global_data_and_code"
          type="global_data_and_codeType" maxOccurs="1" minOccurs="1">
        </xs:element>
        <xs:element name="sequences" type="sequencesType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:sequence>
      <xs:attribute name="locked" type="xs:boolean" use="optional" />
      <xs:attribute name="id" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="descriptionType">
      <xs:sequence>
        <xs:element name="brief" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="copyright" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="introduction" type="textValueType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="global_data_and_codeType">
      <xs:sequence>
        <xs:element name="code_prefix" maxOccurs="1" minOccurs="1"
          type="textValueType">
        </xs:element>
        <xs:element name="global_definitions" maxOccurs="1"
          minOccurs="1" type="codeWrapperType">
        </xs:element>
        <xs:element name="global_code" maxOccurs="1" minOccurs="1" type="codeWrapperType">
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sequencesType">
      <xs:sequence>
        <xs:element name="sequence" type="sequenceType" maxOccurs="unbounded" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="sequenceType">
      <xs:sequence>
        <xs:element name="type" type="typeType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="brief" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="description" maxOccurs="1" minOccurs="1"
          type="textValueType">
        </xs:element>
        <xs:element name="condition" type="conditionType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="shared_code" type="codeWrapperType"
          maxOccurs="1" minOccurs="1">
        </xs:element>
        <xs:element name="cases" type="casesType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="typeType">
      <xs:sequence>
        <xs:element name="value" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Internal Tests"></xs:enumeration>
              <xs:enumeration value="External Tests"></xs:enumeration>
              <xs:enumeration value="Benchmarks"></xs:enumeration>
              <xs:whiteSpace value="collapse"></xs:whiteSpace>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
      <xs:attribute name="index" type="xs:nonNegativeInteger" use="optional" />
    </xs:complexType>

    <xs:complexType name="conditionType">
      <xs:sequence>
        <xs:element name="value" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:whiteSpace value="collapse"></xs:whiteSpace>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="shared_codeType">
      <xs:sequence>
        <xs:element name="value" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:whiteSpace value="collapse"></xs:whiteSpace>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="casesType">
      <xs:sequence>
        <xs:element name="case" type="caseType" maxOccurs="unbounded"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="caseType">
      <xs:sequence>
        <xs:element name="brief" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="description" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="condition" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="various_code" type="various_codeType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="steps" type="stepsType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="various_codeType">
      <xs:sequence>
        <xs:element name="setup_code" type="codeWrapperType"
          maxOccurs="1" minOccurs="1">
        </xs:element>
        <xs:element name="teardown_code" type="codeWrapperType"
          maxOccurs="1" minOccurs="1">
        </xs:element>
        <xs:element name="local_variables" type="codeWrapperType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="codeWrapperType">
      <xs:sequence>
        <xs:element name="value" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:whiteSpace value="collapse"></xs:whiteSpace>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
    <xs:complexType name="stepsType">
      <xs:sequence>
        <xs:element name="step" type="stepType" maxOccurs="unbounded" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="stepType">
      <xs:sequence>
        <xs:element name="description" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="tags" type="textValueType" maxOccurs="1"
          minOccurs="1">
        </xs:element>
        <xs:element name="code" type="codeWrapperType" maxOccurs="1" minOccurs="1"></xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:complexType name="textValueType">
      <xs:sequence>
        <xs:element name="value" maxOccurs="1" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:whiteSpace value="collapse"></xs:whiteSpace>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:element name="instance" type="instanceType"></xs:element>
</xs:schema>

=== chibios-upstream/chibios/test/corebmk/configuration.xml
<instance locked="false"
  id="org.chibios.spc5.components.portable.chibios_unitary_tests_engine"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.chibios.org/xml/schema/unittest.xsd">
  <description>
    <brief>
      <value>Core Benchmarks Test Suite.</value>
    </brief>
    <copyright>
      <value><![CDATA[/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/
/*
    This module is based on the work of John Walker (April of 1989) and
    merely adapted to work in ChibiOS. The author has not specified
    additional license terms so this is released using the most permissive
    license used in ChibiOS. The license covers the changes only, not the
    original work.
 */]]></value>
    </copyright>
    <introduction>
      <value>Test suite for core benchmarks. The purpose of this suite
        is to perform general benchmarks in order to assess
        performance of cores and/or compilers.
      </value>
    </introduction>
  </description>
  <global_data_and_code>
    <code_prefix>
      <value>corebmk_</value>
    </code_prefix>
    <global_definitions>
      <value><![CDATA[
/**/
]]></value>
    </global_definitions>
    <global_code>
      <value><![CDATA[
/**/
]]></value>
    </global_code>
  </global_data_and_code>
  <sequences>
    <sequence>
      <type index="0">
        <value>Internal Tests</value>
      </type>
      <brief>
        <value>Information.</value>
      </brief>
      <description>
        <value>This sequence reports configuration and version
          information about execution environment.
        </value>
      </description>
      <condition>
        <value><![CDATA[CH_CFG_USE_HEAP == TRUE]]></value>
      </condition>
      <shared_code>
        <value><![CDATA[
#include <string.h>

#include "ch.h"

#include "ffbench_mod.h"

#define ASIZE       64              /* Array edge size.                     */
#define NITERATIONS 10              /* Number of iterations.                */
#define NPASSES     50              /* Number of FFT/Inverse passes.        */

#define max(a, b)   ((a) > (b) ? (a) : (b))
#define min(a, b)   ((a) <= (b) ? (a) : (b))

float *fdatas;
double *fdatad;
]]></value>
      </shared_code>
      <cases>
        <case>
          <brief>
            <value>Environment Info.</value>
          </brief>
          <description>
            <value>Environment-related info are reported.</value>
          </description>
          <condition>
            <value />
          </condition>
          <various_code>
            <setup_code>
              <value />
            </setup_code>
            <teardown_code>
              <value />
            </teardown_code>
            <local_variables>
              <value />
            </local_variables>
          </various_code>
          <steps>
            <step>
              <description>
                <value>Architecture and Compiler information.</value>
              </description>
              <tags>
                <value />
              </tags>
              <code>
                <value><![CDATA[
#if defined(PORT_ARCHITECTURE_NAME)
test_print("--- Architecture:                       ");
test_println(PORT_ARCHITECTURE_NAME);
#endif
#if defined(PORT_CORE_VARIANT_NAME)
test_print("--- Core Variant:                       ");
test_println(PORT_CORE_VARIANT_NAME);
#endif
#if defined(PORT_COMPILER_NAME)
test_print("--- Compiler:                           ");
test_println(PORT_COMPILER_NAME);
#endif
#if defined(PORT_INFO)
test_print("--- Port Info:                          ");
test_println(PORT_INFO);
#endif
#if defined(PORT_NATURAL_ALIGN)
test_print("--- Natural alignment:                  ");
test_printn(PORT_NATURAL_ALIGN);
test_println("");
#endif
#if defined(PORT_STACK_ALIGN)
test_print("--- Stack alignment:                    ");
test_printn(PORT_STACK_ALIGN);
test_println("");
#endif
#if defined(PORT_WORKING_AREA_ALIGN)
test_print("--- Working area alignment:             ");
test_printn(PORT_WORKING_AREA_ALIGN);
test_println("");
#endif
]]></value>
              </code>
            </step>
          </steps>
        </case>
        <case>
          <brief>
            <value>Two-dimensional FFT</value>
          </brief>
          <description>
            <value>Two-dimensional FFT benchmark, execution time is reported, expected results are checked.</value>
          </description>
          <condition>
            <value />
          </condition>
          <various_code>
            <setup_code>
              <value><![CDATA[
fdatas = NULL;
]]></value>
            </setup_code>
            <teardown_code>
              <value><![CDATA[
if (fdatas != NULL) {
  chHeapFree((void *)fdatas);
}
]]></value>
            </teardown_code>
            <local_variables>
              <value><![CDATA[
time_msecs_t msecs;
size_t fasize;
int fanum;
int faedge;
int nsize[] = {0, 0, 0};
]]></value>
            </local_variables>
          </various_code>
          <steps>
            <step>
              <description>
                <value>Allocating memory for single precision work matrix</value>
              </description>
              <tags>
                <value />
              </tags>
              <code>
                <value><![CDATA[
faedge = ASIZE;                                     /* FFT array edge size.*/
fanum  = faedge * faedge;
fasize = ((size_t)(fanum + 1) * 2 * sizeof(float)); /* FFT array size.*/
fdatas = (float *)chHeapAlloc(NULL, fasize);
nsize[1] = nsize[2] = faedge;

test_assert(fdatas != NULL, "single precision matrix allocation failed");
]]></value>
              </code>
            </step>
            <step>
              <description>
                <value>Printing setup</value>
              </description>
              <tags>
                <value />
              </tags>
              <code>
                <value><![CDATA[
test_print("--- Matrix: ");
test_printn(ASIZE);
test_print("x");
test_printn(ASIZE);
test_println("");
test_print("--- Iter. : ");
test_printn(NITERATIONS);
test_println("");
test_print("--- Passes: ");
test_printn(NPASSES);
test_println("");
]]></value>
              </code>
            </step>
            <step>
              <description>
                <value>Running single precision FFT iterations</value>
              </description>
              <tags>
                <value />
              </tags>
              <code>
                <value><![CDATA[
systime_t start, end;
int i, j, k, iters;

/* Time stamp for benchmark start.*/
start = chVTGetSystemTime();

iters = 0;
for (k = 0; k < NITERATIONS; k++) {

  /* Generate data array to process.*/
  memset(fdatas, 0, fasize);
  for (i = 0; i < faedge; i++) {
    for (j = 0; j < faedge; j++) {
      if (((i & 15) == 8) || ((j & 15) == 8)) {
        fdatas[1 + ((faedge * i) + j) * 2] = 128.0;
      }
    }
  }

  for (i = 0; i < NPASSES; i++) {
    /* Transform image to frequency domain.*/
    fourn_float(fdatas, nsize, 2, 1);

    /* Back-transform to image.*/
    fourn_float(fdatas, nsize, 2, -1);

    iters++;
  }
}

/* Time stamp for benchmark end.*/
end = chVTGetSystemTime();
msecs = chTimeI2MS(chTimeDiffX(start, end));
]]></value>
              </code>
            </step>
            <step>
              <description>
                <value>Printing execution time</value>
              </description>
              <tags>
                <value />
              </tags>
              <code>
                <value><![CDATA[
test_print("--- Time  : ");
test_printn(msecs);
test_println(" milliseconds");
]]></value>
              </code>
            </step>
          </steps>
        </case>
      </cases>
    </sequence>
  </sequences>
</instance>

=== chibios-upstream/chibios/os/test/ftl/xml/configuration.xml
<?xml version="1.0" encoding="UTF-8"?>
<instance
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.chibios.org/xml/schema/unittest.xsd">
  <description>
    <brief>
      <value>Example Test Suite.</value>
    </brief>
    <copyright>
      <value><![CDATA[/*
    ChibiOS - Copyright (C) 2006-2026 Giovanni Di Sirio.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
*/]]></value>
    </copyright>
    <introduction>
      <value>Test suite for EXAMPLE. The purpose of this suite is to
        perform unit tests on the EXAMPLE modules.</value>
    </introduction>
  </description>
  <global_data_and_code>
    <code_prefix>
      <value>example_</value>
    </code_prefix>
    <global_definitions>
      <value><![CDATA[
#define EXAMPLE_GLOBAL_DEFINITIONS_HERE 1
]]></value>
    </global_definitions>
    <global_code>
      <value><![CDATA[
#define EXAMPLE_GLOBAL_CODE_HERE 1
]]></value>
    </global_code>
  </global_data_and_code>
  <sequences>
    <sequence>
      <type>
        <value>Internal Tests</value>
      </type>
      <brief>
        <value>This is a sequence.</value>
      </brief>
      <description>
        <value>A sequence is a collection of test cases executed in sequence
sharing static code and data.</value>
      </description>
      <condition>
        <value />
      </condition>
      <shared_code>
        <value><![CDATA[
#include "example.h"
]]></value>
      </shared_code>
      <cases>
        <case>
          <brief>
            <value>This is a test case.</value>
          </brief>
          <description>
            <value>A test case is a small program testing a specific feature
of the system under test. Test cases should not depend on things done in
previous test cases because those could have failed leaving an unexpected
state.</value>
          </description>
          <condition>
            <value />
          </condition>
          <various_code>
            <setup_code>
              <value><![CDATA[
/* Put here code that prepares for the test case execution, this code is
   executed before the test case.*/
]]></value>
            </setup_code>
            <teardown_code>
              <value><![CDATA[
/* Put here code undoes what the test cases did, as a good practice this code
   should be able to undo things regardles of how the test case succeeded or
   failed.*/
]]></value>
            </teardown_code>
            <local_variables>
              <value><![CDATA[
/* Declare here automatic variables used in the test case, it is good practice
   to not initialize values here.*/
]]></value>
            </local_variables>
          </various_code>
          <steps>
            <step>
              <description>
                <value>This is a test case step. A step is an elementary
piece of code part of a test case.</value>
              </description>
              <tags>
                <value />
              </tags>
              <code>
                <value><![CDATA[
/* Put here the step code.*/
]]></value>
              </code>
            </step>
          </steps>
        </case>
      </cases>
    </sequence>
  </sequences>
</instance>
